name = "cozydoks"
description = "Cozy Doks is a Zola theme helping you build modern documentation websites, which is a fork of AdiDoks theme for Zola."
license = "MIT"
homepage = "https://github.com/jehrhardt/cozydoks"
min_version = "0.19.0"
demo = "https://cozycoder.app/"

[extra]

[author]
name = "Jan Ehrhardt"
homepage = "https://github.com/jehrhardt"

[original]
author = "Aaran Xu"
homepage = "https://github.com/aaranxu"
repo = "https://github.com/aaranxu/adidoks"
